<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlanningBriefingReguaSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('planning_briefing_reguas')->insert([

            // 🧠 1. Personalidade da Marca / Site
            [
                'category' => 'Personalidade da Marca / Site',
                'question' => 'O estilo deve ser mais tradicional ou inovador?',
                'label_left' => 'Tradicional',
                'label_right' => 'Inovador',
                'emoji_left' => '🏛️',
                'emoji_right' => '🚀',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Personalidade da Marca / Site',
                'question' => 'A comunicação deve ser mais formal ou descontraída?',
                'label_left' => 'Formal',
                'label_right' => 'Descontraído',
                'emoji_left' => '🧳',
                'emoji_right' => '😎',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Personalidade da Marca / Site',
                'question' => 'O layout deve ser mais minimalista ou detalhado?',
                'label_left' => 'Minimalista',
                'label_right' => 'Detalhado',
                'emoji_left' => '⚪',
                'emoji_right' => '🎨',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Personalidade da Marca / Site',
                'question' => 'A identidade visual deve tender ao masculino ou feminino?',
                'label_left' => 'Masculino',
                'label_right' => 'Feminino',
                'emoji_left' => '🖤',
                'emoji_right' => '💖',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Personalidade da Marca / Site',
                'question' => 'As cores devem ser mais frias ou quentes?',
                'label_left' => 'Frias',
                'label_right' => 'Quentes',
                'emoji_left' => '❄️',
                'emoji_right' => '🔥',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Personalidade da Marca / Site',
                'question' => 'O estilo deve ser mais simples ou sofisticado?',
                'label_left' => 'Simples',
                'label_right' => 'Sofisticado',
                'emoji_left' => '💡',
                'emoji_right' => '💎',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Personalidade da Marca / Site',
                'question' => 'O tom da marca deve ser mais sério ou divertido?',
                'label_left' => 'Sério',
                'label_right' => 'Divertido',
                'emoji_left' => '⚖️',
                'emoji_right' => '🎉',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 🧭 2. Público e Comunicação
            [
                'category' => 'Público e Comunicação',
                'question' => 'Seu público é mais jovem ou maduro?',
                'label_left' => 'Jovem',
                'label_right' => 'Maduro',
                'emoji_left' => '🧒',
                'emoji_right' => '👨‍💼',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Público e Comunicação',
                'question' => 'Seu público é mais técnico ou leigo?',
                'label_left' => 'Técnico',
                'label_right' => 'Leigo',
                'emoji_left' => '💻',
                'emoji_right' => '💬',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Público e Comunicação',
                'question' => 'Seu público é mais local ou nacional?',
                'label_left' => 'Local',
                'label_right' => 'Nacional',
                'emoji_left' => '📍',
                'emoji_right' => '🌎',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Público e Comunicação',
                'question' => 'O tom da comunicação deve ser mais informativo ou inspiracional?',
                'label_left' => 'Informativo',
                'label_right' => 'Inspiracional',
                'emoji_left' => '📄',
                'emoji_right' => '✨',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Público e Comunicação',
                'question' => 'O público é mais masculino ou feminino?',
                'label_left' => 'Masculino',
                'label_right' => 'Feminino',
                'emoji_left' => '🖤',
                'emoji_right' => '💖',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Público e Comunicação',
                'question' => 'O público tem perfil mais popular ou premium?',
                'label_left' => 'Popular',
                'label_right' => 'Premium',
                'emoji_left' => '💸',
                'emoji_right' => '💎',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ⚙️ 3. Objetivos
            [
                'category' => 'Objetivos',
                'question' => 'O foco principal é institucional ou comercial?',
                'label_left' => 'Institucional',
                'label_right' => 'Comercial',
                'emoji_left' => '🏢',
                'emoji_right' => '🛍️',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Objetivos',
                'question' => 'O site deve priorizar vendas diretas ou geração de leads?',
                'label_left' => 'Vendas diretas',
                'label_right' => 'Geração de leads',
                'emoji_left' => '💳',
                'emoji_right' => '📩',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Objetivos',
                'question' => 'A prioridade é performance ou estilo visual?',
                'label_left' => 'Performance',
                'label_right' => 'Estilo visual',
                'emoji_left' => '⚡',
                'emoji_right' => '🎨',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Objetivos',
                'question' => 'O conteúdo deve focar em texto ou imagens/vídeos?',
                'label_left' => 'Texto',
                'label_right' => 'Imagens e vídeos',
                'emoji_left' => '✍️',
                'emoji_right' => '📷',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Objetivos',
                'question' => 'O foco geral é mais imagem institucional ou resultado prático?',
                'label_left' => 'Imagem institucional',
                'label_right' => 'Resultado / Conversão',
                'emoji_left' => '🏛️',
                'emoji_right' => '💰',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 🧩 4. Estilo Visual
            [
                'category' => 'Estilo Visual',
                'question' => 'O design deve ter aparência mais escura ou clara?',
                'label_left' => 'Escuro',
                'label_right' => 'Claro',
                'emoji_left' => '🌑',
                'emoji_right' => '☀️',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Estilo Visual',
                'question' => 'Prefere um visual mais simples ou mais realista/profundo?',
                'label_left' => 'Simples / Minimalista',
                'label_right' => 'Realista / Profundo',
                'emoji_left' => '⚪',
                'emoji_right' => '🧊',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Estilo Visual',
                'question' => 'Prefere elementos ilustrados ou fotográficos?',
                'label_left' => 'Ilustrado',
                'label_right' => 'Fotográfico',
                'emoji_left' => '✏️',
                'emoji_right' => '📸',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Estilo Visual',
                'question' => 'Os elementos devem ser mais geométricos ou orgânicos?',
                'label_left' => 'Geométrico',
                'label_right' => 'Orgânico',
                'emoji_left' => '⬜',
                'emoji_right' => '🌿',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category' => 'Estilo Visual',
                'question' => 'A estética deve remeter ao retrô ou futurista?',
                'label_left' => 'Retrô',
                'label_right' => 'Futurista',
                'emoji_left' => '📺',
                'emoji_right' => '🤖',
                'min' => -2,
                'max' => 2,
                'step' => 1,
                'default_value' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
