<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QualitativeTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $data = [

            /* 🧠 1. PÚBLICO E SEGMENTO */
            [
                'service_type' => 'global',
                'category' => 'Público e Segmento',
                'question' => 'Quem é o público principal que você deseja atingir?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: jovens entre 20 e 30 anos, interessados em cultura pop.',
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Público e Segmento',
                'question' => 'Há outros públicos secundários importantes?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: profissionais do setor, imprensa, parceiros.',
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Público e Segmento',
                'question' => 'O público já conhece a sua marca?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Parcialmente', 'Não']),
                'placeholder' => null,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Público e Segmento',
                'question' => 'Onde o público encontra sua marca atualmente?',
                'type' => 'multi_choice',
                'options' => json_encode(['Instagram', 'Google', 'Indicação', 'YouTube', 'Outro']),
                'placeholder' => null,
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Público e Segmento',
                'question' => 'Quais hábitos de consumo esse público possui?',
                'type' => 'multi_choice',
                'options' => json_encode(['Compra online', 'Prefere lojas físicas', 'Assina serviços mensais', 'Compra por impulso', 'Pesquisa antes de comprar']),
                'placeholder' => null,
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Público e Segmento',
                'question' => 'Quais redes sociais seu público mais utiliza?',
                'type' => 'multi_choice',
                'options' => json_encode(['Instagram', 'TikTok', 'LinkedIn', 'Facebook', 'X (Twitter)', 'YouTube']),
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Público e Segmento',
                'question' => 'Seu público é mais sensível a preço ou qualidade?',
                'type' => 'choice',
                'options' => json_encode(['Preço', 'Equilíbrio', 'Qualidade']),
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Público e Segmento',
                'question' => 'Como você descreveria o estilo de vida do seu público?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: prático, conectado, familiar, aspiracional...',
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Público e Segmento',
                'question' => 'Quais problemas o seu público enfrenta que o seu produto/serviço resolve?',
                'type' => 'textarea',
                'options' => null,
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Público e Segmento',
                'question' => 'Existe um público que você não quer atingir?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: público de baixa renda, pessoas que não usam tecnologia...',
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            /* ⚔️ 2. CONCORRENTES E DIFERENCIAIS */
            [
                'service_type' => 'global',
                'category' => 'Concorrentes e Diferenciais',
                'question' => 'Liste até 3 concorrentes diretos da sua marca.',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: Apple, Spotify, Notion...',
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Concorrentes e Diferenciais',
                'question' => 'O que você admira nesses concorrentes?',
                'type' => 'textarea',
                'options' => null,
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Concorrentes e Diferenciais',
                'question' => 'O que você gostaria de evitar ou fazer diferente?',
                'type' => 'textarea',
                'options' => null,
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Concorrentes e Diferenciais',
                'question' => 'Envie links de sites ou marcas que você considera referência.',
                'type' => 'file',
                'options' => null,
                'placeholder' => 'Envie links, PDFs ou imagens de referência.',
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Concorrentes e Diferenciais',
                'question' => 'O que torna sua marca única em relação aos concorrentes?',
                'type' => 'textarea',
                'options' => null,
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Concorrentes e Diferenciais',
                'question' => 'Se pudesse se inspirar em uma empresa famosa, qual seria e por quê?',
                'type' => 'textarea',
                'options' => null,
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Concorrentes e Diferenciais',
                'question' => 'Você acompanha seus concorrentes nas redes sociais?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Às vezes', 'Não']),
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Concorrentes e Diferenciais',
                'question' => 'Quais elementos do site dos concorrentes você gostaria de incorporar?',
                'type' => 'multi_choice',
                'options' => json_encode(['Layout', 'Cores', 'Navegação', 'Textos', 'Imagens']),
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Concorrentes e Diferenciais',
                'question' => 'Você sente que está à frente ou atrás da concorrência digitalmente?',
                'type' => 'choice',
                'options' => json_encode(['À frente', 'Equilibrado', 'Atrás']),
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Concorrentes e Diferenciais',
                'question' => 'O que você acredita que seu público valoriza mais em você?',
                'type' => 'textarea',
                'options' => null,
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            /* 🎨 3. ESTILO VISUAL / REFERÊNCIAS */
            [
                'service_type' => 'global',
                'category' => 'Estilo Visual / Referências',
                'question' => 'Quais estilos de site ou design você gosta?',
                'type' => 'file',
                'options' => null,
                'placeholder' => 'Envie links, imagens ou prints de sites que você admira.',
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Estilo Visual / Referências',
                'question' => 'Há algo que você não quer ver de jeito nenhum no seu site?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: sites escuros, fontes serifadas, animações exageradas...',
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Estilo Visual / Referências',
                'question' => 'Como você gostaria que as pessoas se sentissem ao visitar o site?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: inspiradas, acolhidas, impactadas, seguras...',
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Estilo Visual / Referências',
                'question' => 'Prefere um estilo mais moderno ou tradicional?',
                'type' => 'choice',
                'options' => json_encode(['Moderno', 'Tradicional', 'Intermediário']),
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Estilo Visual / Referências',
                'question' => 'Que tipo de cores você mais se identifica?',
                'type' => 'choice',
                'options' => json_encode(['Cores frias', 'Cores quentes', 'Cores neutras', 'Mistura']),
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Estilo Visual / Referências',
                'question' => 'Há alguma marca cuja estética você gostaria de seguir como referência?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: Netflix, Apple, Discord...',
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Estilo Visual / Referências',
                'question' => 'Prefere um visual mais ilustrado ou mais fotográfico?',
                'type' => 'choice',
                'options' => json_encode(['Ilustrado', 'Fotográfico', 'Ambos']),
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Estilo Visual / Referências',
                'question' => 'Você deseja usar muitas animações ou algo mais estático?',
                'type' => 'choice',
                'options' => json_encode(['Dinâmico', 'Equilibrado', 'Minimalista']),
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Estilo Visual / Referências',
                'question' => 'Há elementos visuais que representam bem a sua marca?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: triângulos, linhas, ondas, luzes, etc.',
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Estilo Visual / Referências',
                'question' => 'Envie arquivos de identidade visual, logotipos ou guias de marca, se tiver.',
                'type' => 'file',
                'options' => null,
                'placeholder' => 'Arquivos .png, .pdf, .zip...',
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            /* ⚙️ 4. FUNCIONALIDADES DESEJADAS */
            [
                'service_type' => 'global',
                'category' => 'Funcionalidades Desejadas',
                'question' => 'Quais funcionalidades principais você precisa?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: blog, login, galeria de imagens, formulário de contato...',
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Funcionalidades Desejadas',
                'question' => 'Seu projeto precisará de área restrita (usuários, login, painel)?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Não', 'Talvez futuramente']),
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Funcionalidades Desejadas',
                'question' => 'Deseja integração com algum serviço externo?',
                'type' => 'multi_choice',
                'options' => json_encode(['Redes sociais', 'Pagamentos', 'Google Maps', 'E-mail Marketing', 'Outro']),
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Funcionalidades Desejadas',
                'question' => 'Você deseja um painel administrativo?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Não', 'Não sei ainda']),
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Funcionalidades Desejadas',
                'question' => 'Há recursos obrigatórios para o lançamento?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: login, área de notícias, busca interna...',
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Funcionalidades Desejadas',
                'question' => 'Você precisa que o projeto seja multiidioma?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Não', 'Talvez no futuro']),
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Funcionalidades Desejadas',
                'question' => 'Quais dispositivos são prioridade?',
                'type' => 'multi_choice',
                'options' => json_encode(['Desktop', 'Mobile', 'Tablet']),
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Funcionalidades Desejadas',
                'question' => 'Você precisa que o site tenha modo escuro?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Não', 'Indiferente']),
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Funcionalidades Desejadas',
                'question' => 'O projeto deve permitir comentários, curtidas ou avaliações?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Não', 'Talvez futuramente']),
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Funcionalidades Desejadas',
                'question' => 'Envie exemplos de sites que possuem as funcionalidades que você deseja.',
                'type' => 'file',
                'options' => null,
                'placeholder' => 'Arquivos, prints ou links de referência.',
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            /* 🗣️ 5. TONALIDADE DA COMUNICAÇÃO */
            [
                'service_type' => 'global',
                'category' => 'Tonalidade da Comunicação',
                'question' => 'Como você descreveria o tom ideal da sua marca?',
                'type' => 'choice',
                'options' => json_encode(['Formal', 'Descontraído', 'Inspirador', 'Divertido', 'Técnico']),
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Tonalidade da Comunicação',
                'question' => 'Há alguma frase, slogan ou lema que represente sua marca?',
                'type' => 'text',
                'options' => null,
                'placeholder' => 'Ex: “Transformando ideias em experiências digitais.”',
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Tonalidade da Comunicação',
                'question' => 'Como você quer que sua marca soe ao público?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: acolhedora, confiante, moderna...',
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Tonalidade da Comunicação',
                'question' => 'Seu público entende melhor comunicações curtas ou detalhadas?',
                'type' => 'choice',
                'options' => json_encode(['Curtas e diretas', 'Detalhadas e explicativas']),
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Tonalidade da Comunicação',
                'question' => 'Há palavras ou expressões que você quer evitar?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: jargões técnicos, termos antiquados...',
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Tonalidade da Comunicação',
                'question' => 'Você deseja que o texto use emojis, gírias ou linguagem mais casual?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Apenas de leve', 'Não']),
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Tonalidade da Comunicação',
                'question' => 'A comunicação deve transmitir mais emoção ou racionalidade?',
                'type' => 'choice',
                'options' => json_encode(['Mais emoção', 'Equilíbrio', 'Mais racionalidade']),
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Tonalidade da Comunicação',
                'question' => 'Como você se refere ao público (você, cliente, parceiro...)?',
                'type' => 'text',
                'options' => null,
                'placeholder' => 'Ex: clientes, usuários, membros...',
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Tonalidade da Comunicação',
                'question' => 'Quais marcas você acha que se comunicam de forma parecida com o que deseja?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: Nubank, Apple, Notion, Airbnb...',
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Tonalidade da Comunicação',
                'question' => 'Há alguma cor, som ou símbolo que represente sua forma de se comunicar?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: laranja vibrante, som de notificação, raio, coração...',
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            /* 📄 6. CONTEÚDO E ATUALIZAÇÃO */
            [
                'service_type' => 'global',
                'category' => 'Conteúdo e Atualização',
                'question' => 'Você já possui os textos e imagens do site prontos?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Parcialmente', 'Não']),
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Conteúdo e Atualização',
                'question' => 'Quem será responsável por atualizar o conteúdo do site após o lançamento?',
                'type' => 'choice',
                'options' => json_encode(['Minha equipe', 'MM Criativos', 'Outro parceiro']),
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Conteúdo e Atualização',
                'question' => 'Com que frequência você pretende atualizar o site?',
                'type' => 'choice',
                'options' => json_encode(['Diariamente', 'Semanalmente', 'Mensalmente', 'Pouco frequentemente']),
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Conteúdo e Atualização',
                'question' => 'Você precisa de uma área de blog ou notícias?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Não', 'Talvez futuramente']),
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Conteúdo e Atualização',
                'question' => 'Quais tipos de conteúdo serão mais frequentes?',
                'type' => 'multi_choice',
                'options' => json_encode(['Artigos', 'Vídeos', 'Produtos', 'Portfólios', 'Notícias']),
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Conteúdo e Atualização',
                'question' => 'Você possui redatores ou produtores de conteúdo?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Não', 'Pretendo contratar']),
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Conteúdo e Atualização',
                'question' => 'Há conteúdos obrigatórios para o lançamento?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: sobre, portfólio, blog, contato...',
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Conteúdo e Atualização',
                'question' => 'Você deseja que o site tenha suporte para vídeos ou podcasts?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Não', 'Talvez futuramente']),
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Conteúdo e Atualização',
                'question' => 'Há conteúdos que precisam ser protegidos ou acessíveis apenas a usuários logados?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Não', 'Não sei ainda']),
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Conteúdo e Atualização',
                'question' => 'Envie arquivos ou textos que já deseja usar no site.',
                'type' => 'file',
                'options' => null,
                'placeholder' => 'Arquivos .docx, .txt, .pdf, imagens...',
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            /* 💭 7. EXPECTATIVAS E MEDOS */
            [
                'service_type' => 'global',
                'category' => 'Expectativas e Medos',
                'question' => 'O que você mais espera alcançar com este projeto?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: aumentar as vendas, reforçar a marca, digitalizar o negócio...',
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Expectativas e Medos',
                'question' => 'Qual seria o principal sinal de sucesso pra você após o lançamento?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: receber elogios, mais visitas, novos leads...',
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Expectativas e Medos',
                'question' => 'Você tem alguma meta numérica em mente?',
                'type' => 'text',
                'options' => null,
                'placeholder' => 'Ex: 1000 visitas/mês, 10 vendas por dia...',
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Expectativas e Medos',
                'question' => 'O que você mais teme que aconteça durante o projeto?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: atrasos, dificuldade de comunicação, resultado insatisfatório...',
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Expectativas e Medos',
                'question' => 'Qual foi sua pior experiência anterior com um projeto ou agência?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: não cumpriram prazos, não entenderam a proposta...',
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Expectativas e Medos',
                'question' => 'O que te deixaria mais tranquilo durante o processo?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: atualizações semanais, acesso ao progresso, comunicação direta...',
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Expectativas e Medos',
                'question' => 'Como você define sucesso para este projeto?',
                'type' => 'choice',
                'options' => null,
                'options' => json_encode(['Resultado financeiro', 'Reconhecimento da marca', 'Facilidade de uso', 'Experiência visual']),
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Expectativas e Medos',
                'question' => 'Há algo que você teme perder com a mudança ou novo projeto?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: identidade antiga, posicionamento, público atual...',
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Expectativas e Medos',
                'question' => 'Você deseja participar ativamente do processo de criação?',
                'type' => 'choice',
                'options' => json_encode(['Sim, quero acompanhar tudo', 'Prefiro só aprovar etapas', 'Confio na equipe para decidir']),
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Expectativas e Medos',
                'question' => 'Há algo que você acredita que possa dificultar o andamento do projeto?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: falta de tempo, equipe pequena, indefinição de conteúdo...',
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            /* ⏱️ 8. PRAZOS E ENTREGÁVEIS ESPERADOS */
            [
                'service_type' => 'global',
                'category' => 'Prazos e Entregáveis Esperados',
                'question' => 'Existe uma data importante relacionada ao lançamento?',
                'type' => 'text',
                'options' => null,
                'placeholder' => 'Ex: evento, campanha, feriado, lançamento de produto...',
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Prazos e Entregáveis Esperados',
                'question' => 'Qual seria o prazo ideal para entrega do projeto?',
                'type' => 'text',
                'options' => null,
                'placeholder' => 'Ex: 30 dias, 2 meses, até o final do trimestre...',
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Prazos e Entregáveis Esperados',
                'question' => 'Você tem algum prazo limite inadiável?',
                'type' => 'text',
                'options' => null,
                'placeholder' => 'Ex: lançamento de produto em 10/12...',
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Prazos e Entregáveis Esperados',
                'question' => 'Como você prefere acompanhar o andamento do projeto?',
                'type' => 'choice',
                'options' => json_encode(['Atualizações semanais', 'Painel online', 'Reuniões quinzenais', 'Somente ao final de cada etapa']),
                'sort_order' => 4,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Prazos e Entregáveis Esperados',
                'question' => 'Você prefere ver versões parciais (protótipos) ou apenas o produto final?',
                'type' => 'choice',
                'options' => json_encode(['Prefiro acompanhar versões', 'Apenas o final', 'Depende do projeto']),
                'sort_order' => 5,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Prazos e Entregáveis Esperados',
                'question' => 'Quais entregáveis você espera ao final do projeto?',
                'type' => 'multi_choice',
                'options' => json_encode(['Site completo', 'Design no Figma', 'Painel administrativo', 'Documentação', 'Relatório SEO']),
                'sort_order' => 6,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Prazos e Entregáveis Esperados',
                'question' => 'Você precisa de treinamento sobre como usar o site/sistema?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Não', 'Talvez']),
                'sort_order' => 7,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Prazos e Entregáveis Esperados',
                'question' => 'Após o projeto, você deseja contratar manutenção mensal?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Não', 'Talvez futuramente']),
                'sort_order' => 8,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Prazos e Entregáveis Esperados',
                'question' => 'Você precisa que o projeto esteja publicado e hospedado por nós?',
                'type' => 'choice',
                'options' => json_encode(['Sim', 'Não', 'Ainda vou decidir']),
                'sort_order' => 9,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'service_type' => 'global',
                'category' => 'Prazos e Entregáveis Esperados',
                'question' => 'Há alguma dependência externa que possa impactar o prazo?',
                'type' => 'textarea',
                'options' => null,
                'placeholder' => 'Ex: aprovação de terceiros, fotos, textos, integração com sistemas...',
                'sort_order' => 10,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];
        // 🧱 Padroniza colunas antes de inserir (seguro até com arrays longos)
        $data = array_map(fn($item) => array_merge([
            'service_type' => null,
            'category' => null,
            'question' => null,
            'type' => 'text',
            'options' => null,
            'placeholder' => null,
            'sort_order' => 0,
            'is_active' => true,
            'created_at' => $now,
            'updated_at' => $now,
        ], $item), $data);

        DB::table('qualitative_templates')->insert($data);
    }
}
