services:
  app:
    build: .
    working_dir: /app

    volumes:
      - ./:/app

    environment:
      APP_ENV: production
      APP_DEBUG: false
      WEB_DOCUMENT_ROOT: /app/public

    # AÇÃO CRÍTICA: Sintaxe de Bloco (|) para segurança de parsing
    command: |
      sh -c "
        # Espera longa para o DB resolver o nome de host
        sleep 25 &&
        composer install --no-dev --optimize-autoloader &&
        php artisan migrate --force &&
        php artisan optimize &&
        supervisord -c /opt/docker/etc/supervisor.conf
      "

    restart: unless-stopped
